M48
; DRILL file KiCad 10.0.3 date 2026-06-09T11:13:52
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-09T11:13:52+05:45
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X51.395Y-64.6
X51.395Y-115.4
X80.605Y-64.6
X80.605Y-115.4
M30
